### ISSUE TITLE
Enter your token

### ISSUE THREAD

**Issue by NA3** [winnieoursbrun/velero-ui#8]
hi, i was testing your ui, i have successfull deployed it but what is the tocken needed for login
if i set a random one i have this:
![Capture](https://user-images.githubusercontent.com/3059879/107098854-8bd9bc00-6810-11eb-95bb-a1c71af7dc48.PNG)

i think it not comunicate with the velero-cli api
regards.

**Comment by winnieoursbrun** [comment]
Hello @NA3 , sorry for not responding since a long time.

This project is actually not working, and i still have so much code to do and push before releasing it as the first version.
You can still keep it in watch if you want to stay updated about it.

Regards.

**Comment by drummerglen** [comment]
@winnieoursbrun Hi~ Is there any update? I just built it in natiive kubernetes, but i met the same problem.
How to get the token manually? Or is it a static token?
Deployment Env:
```
Kubernetes: 1.20.7
Velero: 1.6.0
namespace: velero
serviceAccount: velero
```
