### ISSUE TITLE
i have make something wrong?

### ISSUE THREAD

**Issue by NA3** [winnieoursbrun/velero-ui#9]
`(☸ dev-admin@dev:istio-system)  na3 at k8s in velero-ui on  master via ⬢ v12.18.2 on 🐳 v19.03.11 
❯ yarn install
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "vue-cli-plugin-vuetify > null-loader@3.0.0" has unmet peer dependency "webpack@^4.3.0".
[4/4] Building fresh packages...
Done in 56.84s.
(☸ dev-admin@dev:istio-system)  na3 at k8s in velero-ui on  master via ⬢ v12.18.2 on 🐳 v19.03.11 took 58s 
❯ yarn build                                              
yarn run v1.22.5
$ vue-cli-service build

⠇  Building for production...

 WARNING  Compiled with 3 warnings                                                                                                                                                                       11:29:24 PM

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  fonts/materialdesignicons-webfont.1a95531b.woff (257 KiB)
  fonts/materialdesignicons-webfont.6acc7d6c.ttf (534 KiB)
  fonts/materialdesignicons-webfont.be7691c1.eot (534 KiB)
  img/materialdesignicons-webfont.c68a0a65.svg (4 MiB)
  css/chunk-vendors.41ed3a7f.css (673 KiB)
  js/chunk-vendors.ecb930f7.js (1.06 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.74 MiB)
      css/chunk-vendors.41ed3a7f.css
      js/chunk-vendors.ecb930f7.js
      css/app.7dd8d082.css
      js/app.9da2b109.js

 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                   Size                                                                                Gzipped

  dist/js/chunk-vendors.ecb930f7.js      1081.48 KiB                                                                         260.72 KiB
  dist/js/app.9da2b109.js                26.48 KiB                                                                           6.87 KiB
  dist/css/chunk-vendors.41ed3a7f.css    673.41 KiB                                                                          90.14 KiB
  dist/css/app.7dd8d082.css              0.20 KiB                                                                            0.16 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
Done in 62.96s.
(☸ dev-admin@dev:istio-system)  na3 at k8s in velero-ui on  master via ⬢ v12.18.2 on 🐳 v19.03.11 took 1m 4s 
❯ serve -s dist                                            
ERROR: Cannot copy to clipboard: write EPIPE

   ┌────────────────────────────────────────────────┐
   │                                                │
   │   Serving!                                     │
   │                                                │
   │   - Local:            http://localhost:5000    │
   │   - On Your Network:  http://1.25.52.25:5000   │
   │                                                │
   └────────────────────────────────────────────────┘`

**Comment by winnieoursbrun** [comment]
Hi @NA3,

I'm closing the issue, your answer are in #8 

Regards
